### PR TITLE
Add audit + query logging configuration.

### PR DESCRIPTION
**Pull request by Miles-Garnsey**
Adding audit and query logging for Cassandra 4.0.0.

### CODE REVIEW

**Comment by Miles-Garnsey** [comment]
The addition of the audit logging configs seems to cause an error at startup

```
ERROR [epollEventLoopGroup-7-2] 2021-09-12 08:35:28,062 NoSpamLogger.java:98 - Failed notifying listeners
java.lang.NullPointerException: null
at org.apache.cassandra.audit.AuditLogEntry.getLogString(AuditLogEntry.java:77)
at org.apache.cassandra.audit.BinAuditLogger.log(BinAuditLogger.java:92)
at org.apache.cassandra.audit.AuditLogManager.log(AuditLogManager.java:117)
at org.apache.cassandra.audit.AuditLogManager.querySuccess(AuditLogManager.java:201)
at org.apache.cassandra.cql3.QueryEvents.notifyQuerySuccess(QueryEvents.java:86)
at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:109)
at org.apache.cassandra.transport.Message$Request.execute(Message.java:242)
at org.apache.cassandra.transport.UnixSocketServer4x$UnixSockMessage.channelRead0(UnixSocketServer4x.java:105)
at org.apache.cassandra.transport.UnixSocketServer4x$UnixSockMessage.channelRead0(UnixSocketServer4x.java:85)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Unknown Source)
```

This error suggests that the `getLogString()` function on the `AuditLogEntry.java` class is failing with an NPE. But from what I can see the log entries do produce the `source` field. 

```
ÇversionÄtypeåauditÇmessage¸ëuser:k8ssandra-0-superuser|host:/10.244.3.10:7000|source:/10.244.3.10|port:60914|timestamp:1631439338500|type:CREATE_TABLE|category:DDL|test|scope:test|operation:CREATE TABLE test (col1 int, col2 text, PRIMARY KEY 
```

This will be something to catch up on later to see if we can reduce the log noise, but it doesn't appear to lead to any difficulties.

**Comment by Miles-Garnsey** [comment]
Waiting on further advice as to how we can make query logging work. The problem is that the parent key `full_query_logging_options` should be commented out by default and we need to determine how to support this using EDN.

**Comment by Miles-Garnsey** [comment]
Query logging now also added to the config file. Note that the behaviour here is slightly inconsistent with other configuration options.

Generally, for configuration dicts (nested configs) which are optional, there is an 'enabled' or similar field within the dict e.g. -
```
server_encryption_options:
    internode_encryption: none
```

Internally, the config-builder makes all other fields within the dict dependant on `enabled` (or `internode_encryption` in the above case). This makes it possible to implement a behaviour where the default values and their keys drop out completely if the `enabled` field is not set `true`.

`full_query_logging_options` does not work this way, and is commented out by default. It also has default options though. `cass-config-builder` does not support this, so users will need to manually add the defaults back in when enabling  `full_query_logging_options`.

**Comment by Miles-Garnsey** [comment]
PR tested and confirmed working. Note that for query logging to be enabled you must run `nodetool enablefullquerylog` as well as configuring query logging via `cassandra.yaml`.

**Comment by jdonenine** [comment]
Hey @Miles-Garnsey w.r.t.

> Note that for query logging to be enabled you must run nodetool enablefullquerylog as well as configuring query logging via cassandra.yaml.

This obviously applies to the K8ssandra use cases, but what we've done in other spots where nodetool commands were necessary is create a new API on the management-api to expose the functionality there.

This does then bring up an interesting question that we talked about in retrospective this morning about "what happens if someone upgrades k8ssandra but doesn't upgrade the management API?".  It's a problem we'll have to tackle in a few places where we're exposing new management-api functionality, but it'll certainly be the case here.

**Comment by Miles-Garnsey** [comment]
> Hey @Miles-Garnsey w.r.t.
> 
> > Note that for query logging to be enabled you must run nodetool enablefullquerylog as well as configuring query logging via cassandra.yaml.
> 
> This obviously applies to the K8ssandra use cases, but what we've done in other spots where nodetool commands were necessary is create a new API on the management-api to expose the functionality there.
> 
> This does then bring up an interesting question that we talked about in retrospective this morning about "what happens if someone upgrades k8ssandra but doesn't upgrade the management API?". It's a problem we'll have to tackle in a few places where we're exposing new management-api functionality, but it'll certainly be the case here.

Thanks @jdonenine, I didn't realise that was the practice but it makes sense. Let me go away and raise a new issue against the management API to add this feature.

**Review by emerkle826 — APPROVED** [review]
This looks ok and passes the config-builder unit tests, with the exception of a test failure related to DSE changes recently. I've opened #66 for that, but that does not affect the changes here.

**Pull request merged**
